[report]
skip_covered=True
show_missing=True
sort=cover
; Regexes for lines to exclude from consideration
exclude_also =
    ; TYPE_CHECKING lines are not executed
    if TYPE_CHECKING:

    ; These lines are usually untestable setup code anyway
    if __name__ == "__main__":
