[flake8]
max-line-length = 80
count = True
statistics = True
show-source = True
max-complexity = 11
; Reason for global ignoring of flake8 warnings
; E203 is not PEP8 compliant see https://github.com/psf/black/issues/1859
; W503 is the opposite of the PEP8 recommendation "For new code Knuth's
;      style is suggested." ... where Knuth's style is to break before the
;      operator
ignore = E203,W503 
per_file_ignores =
    ; Make flake8 ignore late module imports just like Ruff
    utils/tests/*.py: E402
    analyze_har_files/tests/*.py: E402
